# Generated by Django 5.0.4 on 2024-04-11 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machinelearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='current_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
