# Generated by Django 5.0.4 on 2024-04-11 17:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machinelearning', '0002_attendence_current_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='current_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary', models.IntegerField(null=True)),
                ('month', models.CharField(default='', max_length=250)),
                ('current_date', models.DateField(default=django.utils.timezone.now)),
                ('eid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
