# Generated by Django 5.0.3 on 2024-04-03 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_uploadfile_projects_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='created_by',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.ManyToManyField(blank=True, to='public.uploadfile'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
