# Generated by Django 5.0.3 on 2024-04-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_remove_projects_created_by_task_assigned_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='endtime',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='startedtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
