# Generated by Django 5.0.3 on 2024-04-03 05:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_task_endtime_task_startedtime_alter_register_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='startedtime',
        ),
        migrations.CreateModel(
            name='timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workinghours', models.IntegerField(null=True)),
                ('current_date', models.DateField(default=django.utils.timezone.now)),
                ('assigned_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.projects')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.task')),
            ],
        ),
    ]
