# Generated by Django 5.0.3 on 2024-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_remove_task_endtime_remove_task_startedtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='designation',
        ),
        migrations.AddField(
            model_name='register',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
