# Generated by Django 5.0.2 on 2024-04-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_remove_register_designation_register_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='file',
        ),
        migrations.AddField(
            model_name='projects',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
