# Generated by Django 5.0.2 on 2024-04-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_remove_projects_file_projects_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
