# Generated by Django 5.0.2 on 2024-04-09 03:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_remove_task_file_task_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='subtasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('current_date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('assigned_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.task')),
            ],
        ),
    ]
