# Generated by Django 5.0.2 on 2024-04-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_complaints_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
