# Generated by Django 5.0.2 on 2024-04-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0015_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='Not updated', max_length=250, null=True),
        ),
    ]
