# Generated by Django 5.0.2 on 2024-04-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0017_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='ltype',
            field=models.CharField(choices=[('', 'Select'), ('Full Day', 'Full Day'), ('Half Day', 'Half Day')], max_length=50, null=True),
        ),
    ]
