# Generated by Django 5.0.2 on 2024-04-10 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0020_timesheet_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='current_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 10, 4, 31, 47, 11959, tzinfo=datetime.timezone.utc)),
        ),
    ]
