# Generated by Django 5.0.2 on 2024-04-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0022_alter_timesheet_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
