# Generated by Django 5.0.4 on 2024-04-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0029_alter_register_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendece',
        ),
    ]
